\forestLoadExternal {1}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{S \eliste } [{NP[\type {nom}]} [niemand;nobody] ] [{V$'$\sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [ihn;him] ] [{V \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows]] ] ] }{\forestIncludeExternalCheck {germanic-forest-1}}{\forestIncludeExternal {germanic-forest-1}}
\forestLoadExternal {2}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{S \eliste } [{NP[\type {acc}]} [ihn;him] ] [{V$'$\sliste { NP[\type {acc}] } } [{NP[\type {nom}]} [niemand;nobody] ] [{V \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-2}}{\forestIncludeExternal {germanic-forest-2}}
\forestLoadExternal {3}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]}, name=S [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} }, name=VP [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}] }} [knows] ] [{NP[\type {acc}]} [him] ] ] ] \node [right=4cm] at (S) { = S }; \node [right=4cm] at (VP) { = VP }; }{\forestIncludeExternalCheck {germanic-forest-3}}{\forestIncludeExternal {germanic-forest-3}}
\forestLoadExternal {4}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Kim] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { PP[\type {to}] }} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], PP[\type {to}] }} [gave] ] [{NP[\type {acc}]} [a book, roof] ] ] [{PP[\type {to}]} [to Sandy, roof] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-4}}{\forestIncludeExternal {germanic-forest-4}}
\forestLoadExternal {5}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]}, name=S [{NP[\type {nom}]} [niemand;nobody] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } }}, name = Vs [{NP[\type {acc}]} [ihn;him] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows] ] ] ] \node [right=4cm] at (S) { = S }; \node [right=4cm] at (Vs) { = V$'$ }; }{\forestIncludeExternalCheck {germanic-forest-5}}{\forestIncludeExternal {germanic-forest-5}}
\forestLoadExternal {6}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\spr \ibox {1}]} [\ibox {2}] [{H[\spr \ibox {1} $\oplus $ \sliste { \ibox {2} }]}]] }{\forestIncludeExternalCheck {germanic-forest-6}}{\forestIncludeExternal {germanic-forest-6}}
\forestLoadExternal {7}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{N[\spr \eliste , \comps \eliste ]} [\ibox {1} Det [the]] [{N[\spr \sliste { \ibox {1} }, \comps \eliste ]} [man]]] }{\forestIncludeExternalCheck {germanic-forest-7}}{\forestIncludeExternal {germanic-forest-7}}
\forestLoadExternal {8}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\comps \ibox {1}]} [{H[\comps \sliste { \ibox {2} } $\oplus $ \ibox {1} ]}] [\ibox {2}]] }{\forestIncludeExternalCheck {germanic-forest-8}}{\forestIncludeExternal {germanic-forest-8}}
\forestLoadExternal {9}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], NP[\type {acc}]}} [gives] ] [{NP[\type {acc}]} [him] ] ] [{NP[\type {acc}]} [the book,roof ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-9}}{\forestIncludeExternal {germanic-forest-9}}
\forestLoadExternal {10}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\comps \ibox {1} $\oplus $ \ibox {2}]} [\ibox {3}] [{H[\comps \ibox {1} $\oplus $ \sliste { \ibox {3} } $\oplus $ \ibox {2} ]}]] }{\forestIncludeExternalCheck {germanic-forest-10}}{\forestIncludeExternal {germanic-forest-10}}
\forestLoadExternal {11}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\spr \ibox {1}, \comps \ibox {2}]} [{[\textsc {mod} \ibox {3}, \spr \eliste , \comps \eliste ]}] [{\ibox {3} H[\spr \ibox {1}, \comps \ibox {2}]}]] }{\forestIncludeExternalCheck {germanic-forest-11}}{\forestIncludeExternal {germanic-forest-11}}
\forestLoadExternal {12}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{\nbar } [{Adj[\textsc {mod} \ibox {2}]} [smart]] [{\ibox {2} \nbar } [woman]]] }{\forestIncludeExternalCheck {germanic-forest-12}}{\forestIncludeExternal {germanic-forest-12}}
\forestLoadExternal {13}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [Adv [morgen;tomorrow] ] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everybody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-13}}{\forestIncludeExternal {germanic-forest-13}}
\forestLoadExternal {14}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everybody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [Adv [morgen;tomorrow] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-14}}{\forestIncludeExternal {germanic-forest-14}}
\forestLoadExternal {15}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everbody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [Adv [morgen;tomorrow] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-15}}{\forestIncludeExternal {germanic-forest-15}}
\forestLoadExternal {16}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Peter] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [Adv [often] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [reads] ] [{NP[\type {acc}]} [books] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-16}}{\forestIncludeExternal {germanic-forest-16}}
\forestLoadExternal {17}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Peter] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [reads] ] [{NP[\type {acc}]} [books] ] ] [Adv [often] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-17}}{\forestIncludeExternal {germanic-forest-17}}
\forestLoadExternal {18}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [C$'$ [C [dass;that]] [TP [NP [jeder;everybody,roof]] [T$'$ [VP [V$'$ [NP [diesen Mann;this man, roof]] [V [\trace $_j$]]]] [T [kenn-$_j$ -t;know- -s]]]]]] }{\forestIncludeExternalCheck {germanic-forest-18}}{\forestIncludeExternal {germanic-forest-18}}
\forestLoadExternal {19}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [C$'$ [C [dass;that]] [TP [NP$_i$ [diesen Mann;this man, roof]] [TP [NP [jeder;everybody,roof]] [T$'$ [VP [V$'$ [NP [\trace $_i$]] [V [\trace $_j$]]]] [T [kenn-$_j$ -t;know- -s]]]]]]] }{\forestIncludeExternalCheck {germanic-forest-19}}{\forestIncludeExternal {germanic-forest-19}}

