\forestLoadExternal {1}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{S \eliste } [{NP[\type {nom}]} [niemand;nobody] ] [{V$'$\sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [ihn;him] ] [{V \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows]] ] ] }{\forestIncludeExternalCheck {germanic-forest-1}}{\forestIncludeExternal {germanic-forest-1}}
\forestLoadExternal {2}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{S \eliste } [{NP[\type {acc}]} [ihn;him] ] [{V$'$\sliste { NP[\type {acc}] } } [{NP[\type {nom}]} [niemand;nobody] ] [{V \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-2}}{\forestIncludeExternal {germanic-forest-2}}
\forestLoadExternal {3}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]}, name=S [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} }, name=VP [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}] }} [knows] ] [{NP[\type {acc}]} [him] ] ] ] \node [right=4cm] at (S) { = S }; \node [right=4cm] at (VP) { = VP }; }{\forestIncludeExternalCheck {germanic-forest-3}}{\forestIncludeExternal {germanic-forest-3}}
\forestLoadExternal {4}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Kim] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { PP[\type {to}] }} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], PP[\type {to}] }} [gave] ] [{NP[\type {acc}]} [a book, roof] ] ] [{PP[\type {to}]} [to Sandy, roof] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-4}}{\forestIncludeExternal {germanic-forest-4}}
\forestLoadExternal {5}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]}, name=S [{NP[\type {nom}]} [niemand;nobody] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } }}, name = Vs [{NP[\type {acc}]} [ihn;him] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows] ] ] ] \node [right=4cm] at (S) { = S }; \node [right=4cm] at (Vs) { = V$'$ }; }{\forestIncludeExternalCheck {germanic-forest-5}}{\forestIncludeExternal {germanic-forest-5}}
\forestLoadExternal {6}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\spr \ibox {1}]} [\ibox {2}] [{H[\spr \ibox {1} $\oplus $ \sliste { \ibox {2} }]}]] }{\forestIncludeExternalCheck {germanic-forest-6}}{\forestIncludeExternal {germanic-forest-6}}
\forestLoadExternal {7}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{N[\spr \eliste , \comps \eliste ]} [\ibox {1} Det [the]] [{N[\spr \sliste { \ibox {1} }, \comps \eliste ]} [man]]] }{\forestIncludeExternalCheck {germanic-forest-7}}{\forestIncludeExternal {germanic-forest-7}}
\forestLoadExternal {8}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\comps \ibox {1}]} [{H[\comps \sliste { \ibox {2} } $\oplus $ \ibox {1} ]}] [\ibox {2}]] }{\forestIncludeExternalCheck {germanic-forest-8}}{\forestIncludeExternal {germanic-forest-8}}
\forestLoadExternal {9}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], NP[\type {acc}]}} [gives] ] [{NP[\type {acc}]} [him] ] ] [{NP[\type {acc}]} [the book,roof ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-9}}{\forestIncludeExternal {germanic-forest-9}}
\forestLoadExternal {10}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\comps \ibox {1} $\oplus $ \ibox {2}]} [\ibox {3}] [{H[\comps \ibox {1} $\oplus $ \sliste { \ibox {3} } $\oplus $ \ibox {2} ]}]] }{\forestIncludeExternalCheck {germanic-forest-10}}{\forestIncludeExternal {germanic-forest-10}}
\forestLoadExternal {11}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\spr \ibox {1}, \comps \ibox {2}]} [{[\textsc {mod} \ibox {3}, \spr \eliste , \comps \eliste ]}] [{\ibox {3} H[\spr \ibox {1}, \comps \ibox {2}]}]] }{\forestIncludeExternalCheck {germanic-forest-11}}{\forestIncludeExternal {germanic-forest-11}}
\forestLoadExternal {12}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{\nbar } [{Adj[\textsc {mod} \ibox {2}]} [smart]] [{\ibox {2} \nbar } [woman]]] }{\forestIncludeExternalCheck {germanic-forest-12}}{\forestIncludeExternal {germanic-forest-12}}
\forestLoadExternal {13}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [Adv [morgen;tomorrow] ] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everybody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-13}}{\forestIncludeExternal {germanic-forest-13}}
\forestLoadExternal {14}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everybody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [Adv [morgen;tomorrow] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-14}}{\forestIncludeExternal {germanic-forest-14}}
\forestLoadExternal {15}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everbody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [Adv [morgen;tomorrow] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-15}}{\forestIncludeExternal {germanic-forest-15}}
\forestLoadExternal {16}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Peter] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [Adv [often] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [reads] ] [{NP[\type {acc}]} [books] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-16}}{\forestIncludeExternal {germanic-forest-16}}
\forestLoadExternal {17}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Peter] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [reads] ] [{NP[\type {acc}]} [books] ] ] [Adv [often] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-17}}{\forestIncludeExternal {germanic-forest-17}}
\forestLoadExternal {18}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [C$'$ [C [dass;that]] [TP [NP [jeder;everybody,roof]] [T$'$ [VP [V$'$ [NP [diesen Mann;this man, roof]] [V [\trace $_j$]]]] [T [kenn-$_j$ -t;know- -s]]]]]] }{\forestIncludeExternalCheck {germanic-forest-18}}{\forestIncludeExternal {germanic-forest-18}}
\forestLoadExternal {19}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [C$'$ [C [dass;that]] [TP [NP$_i$ [diesen Mann;this man, roof]] [TP [NP [jeder;everybody,roof]] [T$'$ [VP [V$'$ [NP [\trace $_i$]] [V [\trace $_j$]]]] [T [kenn-$_j$ -t;know- -s]]]]]]] }{\forestIncludeExternalCheck {germanic-forest-19}}{\forestIncludeExternal {germanic-forest-19}}
\forestLoadExternal {20}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [liest$_k$;reads] ] ] [{S$/\!/$V} [NP [Jens;Jens] ] [{V$'$$\!/\!/$V} [NP [das Buch;the book, roof] ] [{\mybox [v1]{V}$\!/\!/$\mybox [v2]{V}} [\_$_k$] ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-20}}{\forestIncludeExternal {germanic-forest-20}}
\forestLoadExternal {21}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C \sliste { S }} [dass;that] ] [S [NP [Jens;Jens] ] [V$'$ [NP [das Buch;the book, roof] ] [V [liest;reads] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-21}}{\forestIncludeExternal {germanic-forest-21}}
\forestLoadExternal {22}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [lacht$_k$;laughs] ] ] [{S$/\!/$V} [NP [er;he] ] [{V$'$$\!/\!/$V} [Adv [nicht;not] ] [{V$'$$\!/\!/$V} [Adv [absichtlich;deliberately] ] [{V$\!/\!/$V} [\_$_k$] ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-22}}{\forestIncludeExternal {germanic-forest-22}}
\forestLoadExternal {23}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [læser$_k$;reads] ] ] [{S$/\!/$V} [NP [Jens;Jens] ] [{VP$\!/\!/$V} [{V$\!/\!/$V} [\_$_k$] ] [NP [bogen;book.\textsc {def}] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-23}}{\forestIncludeExternal {germanic-forest-23}}
\forestLoadExternal {24}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [læser$_k$;reads] ] ] [{S$/\!/$V} [NP [Jens;Jens] ] [{VP$\!/\!/$V} [Adv [ikke;not] ] [{VP$\!/\!/$V} [{V$\!/\!/$V} [\_$_k$] ] [NP [bogen;book.def] ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-24}}{\forestIncludeExternal {germanic-forest-24}}
\forestLoadExternal {25}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP [Chris] ] [S/NP [NP [David] ] [VP/NP [V [saw] ] [NP/NP [\trace ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-25}}{\forestIncludeExternal {germanic-forest-25}}
\forestLoadExternal {26}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP [Chris] ] [S/NP [NP [we] ] [VP/NP [V [think] ] [CP/NP [C [that] ] [S/NP [NP [David] ] [VP/NP [V [saw] ] [NP/NP [\trace ] ] ] ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-26}}{\forestIncludeExternal {germanic-forest-26}}
\forestLoadExternal {27}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H} [\ibox {1}] [H/\ibox {1}]] }{\forestIncludeExternalCheck {germanic-forest-27}}{\forestIncludeExternal {germanic-forest-27}}
\forestLoadExternal {28}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP$_i$ [das Buch;the book, roof] ] [S/NP [V \sliste { S$/\!/$V } [V [liest$_j$;reads] ] ] [S$/\!/$V/NP [NP/NP [\trace $_i$] ] [V$'$$\!/\!/$V [NP [Jens;Jens] ] [V$\!/\!/$V [\_$_j$] ] ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-28}}{\forestIncludeExternal {germanic-forest-28}}
\forestLoadExternal {29}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP$_i$ [bogen;book.\textsc {def}] ] [S/NP [V \sliste { S$/\!/$V } [V [læser$_j$;reads] ] ] [S$/\!/$V/NP [NP [Jens;Jens] ] [VP$\!/\!/$V/NP [V$\!/\!/$V [\_$_j$] ] [NP/NP [\trace $_i$ ] ] ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-29}}{\forestIncludeExternal {germanic-forest-29}}
\forestLoadExternal {30}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ where n children=0{delay=with translation}{} [CP [C$^0$[weil;because, tier=word]] [TopP [DP$_j$ [diese Sonate;this sonata,tier=below,l=31\baselineskip ]] [SubjP [DP$_i$ [der Mann;the man,tier=word]] [ModP [AdvP [wahrscheinlich;probably,l=20\baselineskip ]] [ObjP [DP$_j$ [diese Sonate;this sonata,tier=below]] [NegP [AdvP [nicht;not,tier=word]] [AspP [AdvP [oft;often,tier=word]] [MannP [AdvP [gut;well,tier=word]] [AuxP [VP$_k$ [gespielt;played,tier=word]] [Aux+ [Aux [hat;has,tier=word]] [vP [DP$_i$] [VP$_k$ [V] [DP$_j$ [,phantom,tier=word]]]]]]]]]]]]]] }{\forestIncludeExternalCheck {germanic-forest-30}}{\forestIncludeExternal {germanic-forest-30}}
\forestLoadExternal {31}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C[\spr \eliste , \comps \sliste { \ibox {1} }]} [weil;because]] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [der Mann;the man] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } }} [{NP[\type {acc}]} [ihm;him] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}], NP[\type {dat}] } }} [{NP[\type {acc}]} [ein Buch;a book] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {dat}], NP[\type {acc}]}} [schenkt;gives] ]] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-31}}{\forestIncludeExternal {germanic-forest-31}}
\forestLoadExternal {32}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C[\comps \sliste { \ibox {1} }]} [that]] [{\ibox {1} V\feattab {\spr \sliste { },\\ \comps \sliste { }}} [{\ibox {2} NP[nom]} [the box, roof]] [V\feattab {\spr \sliste { \ibox {2} },\\ \comps \sliste { }} [V\feattab {\spr \sliste { \ibox {2} },\\ \comps \sliste { \ibox {3} }} [was]] [{\ibox {3} V\feattab {\spr \sliste { \ibox {2} },\\ \comps \sliste {}}} [opened]]]]] }{\forestIncludeExternalCheck {germanic-forest-32}}{\forestIncludeExternal {germanic-forest-32}}
\forestLoadExternal {33}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C[\spr \eliste , \comps \sliste { \ibox {1} }]} [weil;because]] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [der Mann;the man,roof] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } }} [{NP[\type {acc}]} [ihm;him] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}], NP[\type {dat}] } }} [{NP[\type {acc}]} [ein Buch;a book,roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {dat}], NP[\type {acc}]}} [schenkt;gives] ]] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-33}}{\forestIncludeExternal {germanic-forest-33}}
\forestLoadExternal {34}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C[\spr \eliste , \comps \sliste { \ibox {1} }]} [because]] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [the man,roof] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } }} [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {dat}], NP[\type {acc}]}} [schenkt;gives] ] [{NP[\type {acc}]} [a book, roof] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}], NP[\type {dat}] } }} [{PP[\type {acc}]} [to him,roof] ] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-34}}{\forestIncludeExternal {germanic-forest-34}}
\forestLoadExternal {35}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]}, name=S [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {}}, name=VP [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}] }} [knows] ] [{NP[\type {acc}]} [him] ] ] ] \node [right=4cm] at (S) { = S }; \node [right=4cm] at (VP) { = VP }; }{\forestIncludeExternalCheck {germanic-forest-35}}{\forestIncludeExternal {germanic-forest-35}}
\forestLoadExternal {36}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Kim] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {}} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { PP[\type {to}] }} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], PP[\type {to}] }} [gave] ] [{NP[\type {acc}]} [a book, roof] ] ] [{PP[\type {to}]} [to Sandy, roof] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-36}}{\forestIncludeExternal {germanic-forest-36}}
\forestLoadExternal {37}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {}} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}] }} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], NP[\type {acc}]}} [gives] ] [{NP[\type {acc}]} [him] ] ] [{NP[\type {acc}]} [the book,roof ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-37}}{\forestIncludeExternal {germanic-forest-37}}
\forestLoadExternal {38}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C[\spr \eliste , \comps \sliste { S }]} [weil;because]] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [der Mann;the man,roof] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } }} [{NP[\type {dat}]} [ihm;him] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}], NP[\type {dat}] }}} [{NP[\type {acc}]} [ein Buch;a book,roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {dat}], NP[\type {acc}]}} [schenkt;gives] ]] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-38}}{\forestIncludeExternal {germanic-forest-38}}
\forestLoadExternal {39}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C[\spr \eliste , \comps \sliste { S }]} [because]] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [the man,roof] ] [{V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } }} [{V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { PP[\type {acc}] } }} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], PP[\type {acc}]}} [gave] ] [{NP[\type {acc}]} [a book, roof] ] ] [{PP[\type {acc}]} [to him,roof] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-39}}{\forestIncludeExternal {germanic-forest-39}}
\forestLoadExternal {40}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Peter] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {}} [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {}} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}] }} [saw] ] [{NP[\type {acc}]} [this] ] ] [{Adv[\textsc {mod} VP]} [yesterday] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-40}}{\forestIncludeExternal {germanic-forest-40}}
\forestLoadExternal {41}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C[\spr \eliste , \comps \sliste { S }]} [at;that]] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Bjarne;Bjarne] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {}} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}] }} [læste;read] ] [{NP[\type {acc}]} [bogen;book.\textsc {def}] ] ] ] ] }{\forestIncludeExternalCheck {germanic-forest-41}}{\forestIncludeExternal {germanic-forest-41}}

