\forest@external {1}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{S \eliste } [{NP[\type {nom}]} [niemand;nobody] ] [{V$'$\sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [ihn;him] ] [{V \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows]] ] ] }{\forest@includeexternal@check {germanic-forest-1}}{\forest@includeexternal {germanic-forest-1}}
\forest@external {2}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{S \eliste } [{NP[\type {acc}]} [ihn;him] ] [{V$'$\sliste { NP[\type {acc}] } } [{NP[\type {nom}]} [niemand;nobody] ] [{V \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows] ] ] ] }{\forest@includeexternal@check {germanic-forest-2}}{\forest@includeexternal {germanic-forest-2}}
\forest@external {3}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]}, name=S [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} }, name=VP [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}] }} [knows] ] [{NP[\type {acc}]} [him] ] ] ] \node [right=4cm] at (S) { = S }; \node [right=4cm] at (VP) { = VP }; }{\forest@includeexternal@check {germanic-forest-3}}{\forest@includeexternal {germanic-forest-3}}
\forest@external {4}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Kim] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { PP[\type {to}] }} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], PP[\type {to}] }} [gave] ] [{NP[\type {acc}]} [a book, roof] ] ] [{PP[\type {to}]} [to Sandy, roof] ] ] ] }{\forest@includeexternal@check {germanic-forest-4}}{\forest@includeexternal {germanic-forest-4}}
\forest@external {5}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]}, name=S [{NP[\type {nom}]} [niemand;nobody] ] [{V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } }}, name = Vs [{NP[\type {acc}]} [ihn;him] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [kennt;knows] ] ] ] \node [right=4cm] at (S) { = S }; \node [right=4cm] at (Vs) { = V$'$ }; }{\forest@includeexternal@check {germanic-forest-5}}{\forest@includeexternal {germanic-forest-5}}
\forest@external {6}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\spr \ibox {1}]} [\ibox {2}] [{H[\spr \ibox {1} $\oplus $ \sliste { \ibox {2} }]}]] }{\forest@includeexternal@check {germanic-forest-6}}{\forest@includeexternal {germanic-forest-6}}
\forest@external {7}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{N[\spr \eliste , \comps \eliste ]} [\ibox {1} Det [the]] [{N[\spr \sliste { \ibox {1} }, \comps \eliste ]} [man]]] }{\forest@includeexternal@check {germanic-forest-7}}{\forest@includeexternal {germanic-forest-7}}
\forest@external {8}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\comps \ibox {1}]} [{H[\comps \sliste { \ibox {2} } $\oplus $ \ibox {1} ]}] [\ibox {2}]] }{\forest@includeexternal@check {germanic-forest-8}}{\forest@includeexternal {germanic-forest-8}}
\forest@external {9}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [nobody] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste {} } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}], NP[\type {acc}]}} [gives] ] [{NP[\type {acc}]} [him] ] ] [{NP[\type {acc}]} [the book,roof ] ] ] ] }{\forest@includeexternal@check {germanic-forest-9}}{\forest@includeexternal {germanic-forest-9}}
\forest@external {10}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H[\comps \ibox {1} $\oplus $ \ibox {2}]} [\ibox {3}] [{H[\comps \ibox {1} $\oplus $ \sliste { \ibox {3} } $\oplus $ \ibox {2} ]}]] }{\forest@includeexternal@check {germanic-forest-10}}{\forest@includeexternal {germanic-forest-10}}
\forest@external {11}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [Adv [morgen;tomorrow] ] [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everybody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-11}}{\forest@includeexternal {germanic-forest-11}}
\forest@external {12}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everybody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [Adv [morgen;tomorrow] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-12}}{\forest@includeexternal {germanic-forest-12}}
\forest@external {13}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [jeder;everbody] ] [V\feattab { \spr \sliste { }, \comps \sliste { NP[\type {nom}] } } [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [Adv [morgen;tomorrow] ] [V\feattab { \spr \sliste { },\\ \comps \sliste { NP[\type {nom}], NP[\type {acc}]}} [liest;reads] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-13}}{\forest@includeexternal {germanic-forest-13}}
\forest@external {14}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Peter] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [Adv [often] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [reads] ] [{NP[\type {acc}]} [books] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-14}}{\forest@includeexternal {germanic-forest-14}}
\forest@external {15}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [{V[\spr \eliste , \comps \eliste ]} [{NP[\type {nom}]} [Peter] ] [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] }, \comps \sliste { } } [V\feattab { \spr \sliste { NP[\type {nom}] },\\ \comps \sliste { NP[\type {acc}]}} [reads] ] [{NP[\type {acc}]} [books] ] ] [Adv [often] ] ] ] }{\forest@includeexternal@check {germanic-forest-15}}{\forest@includeexternal {germanic-forest-15}}
\forest@external {16}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [C$'$ [C [dass;that]] [TP [NP [jeder;everybody,roof]] [T$'$ [VP [V$'$ [NP [diesen Mann;this man, roof]] [V [\trace $_j$]]]] [T [kenn-$_j$ -t;know- -s]]]]]] }{\forest@includeexternal@check {germanic-forest-16}}{\forest@includeexternal {germanic-forest-16}}
\forest@external {17}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [C$'$ [C [dass;that]] [TP [NP$_i$ [diesen Mann;this man, roof]] [TP [NP [jeder;everybody,roof]] [T$'$ [VP [V$'$ [NP [\trace $_i$]] [V [\trace $_j$]]]] [T [kenn-$_j$ -t;know- -s]]]]]]] }{\forest@includeexternal@check {germanic-forest-17}}{\forest@includeexternal {germanic-forest-17}}
\forest@external {18}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}] } } [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}]} }, name=lesen [lesen;read] ] [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}]}, V}, name=wird [wird;will] ] ] \draw [semithick,->] (lesen)..controls +(south east:2) and +(south west:2)..(wird); }{\forest@includeexternal@check {germanic-forest-18}}{\forest@includeexternal {germanic-forest-18}}
\forest@external {19}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \sliste { }} [{NP[\type {nom}]} [keiner;nobody] ] [V\feattab { \sliste { NP[\type {nom}] }} [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}]}} [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}]}} [lesen;read] ] [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}], V }} [wird;will] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-19}}{\forest@includeexternal {germanic-forest-19}}
\forest@external {20}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \sliste { }} [{NP[\type {acc}]} [das Buch;the book, roof] ] [V\feattab { \sliste { NP[\type {acc}] }} [{NP[\type {nom}]} [keiner;nobody] ] [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}] }} [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}]}} [lesen;read] ] [V\feattab { \sliste { NP[\type {nom}], NP[\type {acc}], V }} [wird;will] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-20}}{\forest@includeexternal {germanic-forest-20}}
\forest@external {21}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \vform \type {fin},\\ \comps \ibox {1} $\oplus $ \ibox {2} } [{\ibox {3} V}\feattab { \vform \type {bse},\\ \subj \ibox {1} \sliste { NP[\type {nom}] }, \\ \comps \ibox {2} \sliste { NP[\type {acc}] } } [lesen;read] ] [V\feattab { \vform \type {fin},\\ \comps \ibox {1} $\oplus $ \ibox {2} $\oplus $ \sliste { \ibox {3} } } [wird;will] ] ] }{\forest@includeexternal@check {germanic-forest-21}}{\forest@includeexternal {germanic-forest-21}}
\forest@external {22}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \vform \type {fin},\\ \comps \ibox {1} $\oplus $ \ibox {2} } [{\ibox {4} V\feattab { \vform \type {bse},\\ \subj \ibox {1},\\ \comps \ibox {2} }} [{\ibox {3} V\feattab { \vform \type {bse},\\ \subj \ibox {1} \sliste { NP[\type {nom}] }, \\ \comps \ibox {2} \sliste { NP[\type {acc}] } }} [lesen;read] ] [V\feattab { \vform \type {bse},\\ \subj \ibox {1},\\ \comps \ibox {2} $\oplus $ \sliste { \ibox {3} } } [können;can] ] ] [V\feattab { \vform \type {fin},\\ \comps \ibox {1} $\oplus $ \ibox {2} $\oplus $ \sliste { \ibox {4} } } [wird;will] ] ] }{\forest@includeexternal@check {germanic-forest-22}}{\forest@includeexternal {germanic-forest-22}}
\forest@external {23}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \vform \type {fin},\\ \comps \ibox {1} $\oplus $ \ibox {2} } [V\feattab { \vform \type {fin},\\ \comps \ibox {1} $\oplus $ \ibox {2} $\oplus $ \sliste { \ibox {4} } } [wird;will] ] [{\ibox {4} V\feattab { \vform \type {bse},\\ \subj \ibox {1},\\ \comps \ibox {2} }} [{\ibox {3} V\feattab { \vform \type {bse},\\ \subj \ibox {1} \sliste { NP[\type {nom}] }, \\ \comps \ibox {2} \sliste { NP[\type {acc}] } }} [lesen;read] ] [V\feattab { \vform \type {bse},\\ \subj \ibox {1},\\ \comps \ibox {2} $\oplus $ \sliste { \ibox {3} } } [können;can] ] ] ] }{\forest@includeexternal@check {germanic-forest-23}}{\forest@includeexternal {germanic-forest-23}}
\forest@external {24}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{[\comps \ibox {1}]} [\ibox {2} {[\textsc {lex}+]}] [{[\comps \ibox {1} $\oplus $ \sliste { \ibox {2} }]}]] }{\forest@includeexternal@check {germanic-forest-24}}{\forest@includeexternal {germanic-forest-24}}
\forest@external {25}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{NP[\type {nom}]} [nobody] ] [VP [V[will] ] [VP[V[read] ] [{NP[\type {acc}]} [the book, roof] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-25}}{\forest@includeexternal {germanic-forest-25}}
\forest@external {26}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{NP[\type {nom}]} [somebody] ] [VP [\vbar [V [promised] ] [{NP[\type {acc}]} [him] ] ] [VP [V [to]] [VP [V [read] ] [{NP[\type {acc}]} [the book, roof] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-26}}{\forest@includeexternal {germanic-forest-26}}
\forest@external {27}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [liest$_k$;reads] ] ] [{S$/\!/$V} [NP [Jens;Jens] ] [{V$'$$\!/\!/$V} [NP [das Buch;the book, roof] ] [{\mybox [v1]{V}$\!/\!/$\mybox [v2]{V}} [\_$_k$] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-27}}{\forest@includeexternal {germanic-forest-27}}
\forest@external {28}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [CP [{C \sliste { S }} [dass;that] ] [S [NP [Jens;Jens] ] [V$'$ [NP [das Buch;the book, roof] ] [V [liest;reads] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-28}}{\forest@includeexternal {germanic-forest-28}}
\forest@external {29}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [lacht$_k$;laughs] ] ] [{S$/\!/$V} [NP [er;he] ] [{V$'$$\!/\!/$V} [Adv [nicht;not] ] [{V$'$$\!/\!/$V} [Adv [absichtlich;deliberately] ] [{V$\!/\!/$V} [\_$_k$] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-29}}{\forest@includeexternal {germanic-forest-29}}
\forest@external {30}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [læser$_k$;reads] ] ] [{S$/\!/$V} [NP [Jens;Jens] ] [{VP$\!/\!/$V} [{V$\!/\!/$V} [\_$_k$] ] [NP [bogen;book.\textsc {def}] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-30}}{\forest@includeexternal {germanic-forest-30}}
\forest@external {31}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{V \sliste { S$/\!/$V }} [V [læser$_k$;reads] ] ] [{S$/\!/$V} [NP [Jens;Jens] ] [{VP$\!/\!/$V} [Adv [ikke;not] ] [{VP$\!/\!/$V} [{V$\!/\!/$V} [\_$_k$] ] [NP [bogen;book.def] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-31}}{\forest@includeexternal {germanic-forest-31}}
\forest@external {32}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP [Chris] ] [S/NP [NP [David] ] [VP/NP [V [saw] ] [NP/NP [\trace ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-32}}{\forest@includeexternal {germanic-forest-32}}
\forest@external {33}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP [Chris] ] [S/NP [NP [we] ] [VP/NP [V [think] ] [CP/NP [C [that] ] [S/NP [NP [David] ] [VP/NP [V [saw] ] [NP/NP [\trace ] ] ] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-33}}{\forest@includeexternal {germanic-forest-33}}
\forest@external {34}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ [{H} [\ibox {1}] [H/\ibox {1}]] }{\forest@includeexternal@check {germanic-forest-34}}{\forest@includeexternal {germanic-forest-34}}
\forest@external {35}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP$_i$ [das Buch;the book, roof] ] [S/NP [V \sliste { S$/\!/$V } [V [liest$_j$;reads] ] ] [S$/\!/$V/NP [NP/NP [\trace $_i$] ] [V$'$$\!/\!/$V [NP [Jens;Jens] ] [V$\!/\!/$V [\_$_j$] ] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-35}}{\forest@includeexternal {germanic-forest-35}}
\forest@external {36}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [NP$_i$ [bogen;book.\textsc {def}] ] [S/NP [V \sliste { S$/\!/$V } [V [læser$_j$;reads] ] ] [S$/\!/$V/NP [NP [Jens;Jens] ] [VP$\!/\!/$V/NP [V$\!/\!/$V [\_$_j$] ] [NP/NP [\trace $_i$ ] ] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-36}}{\forest@includeexternal {germanic-forest-36}}
\forest@external {37}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ where n children=0{delay=with translation}{} [CP [C$^0$[weil;because, tier=word]] [TopP [DP$_j$ [diese Sonate;this sonata,tier=below,l=31\baselineskip ]] [SubjP [DP$_i$ [der Mann;the man,tier=word]] [ModP [AdvP [wahrscheinlich;probably,l=20\baselineskip ]] [ObjP [DP$_j$ [diese Sonate;this sonata,tier=below]] [NegP [AdvP [nicht;not,tier=word]] [AspP [AdvP [oft;often,tier=word]] [MannP [AdvP [gut;well,tier=word]] [AuxP [VP$_k$ [gespielt;played,tier=word]] [Aux+ [Aux [hat;has,tier=word]] [vP [DP$_i$] [VP$_k$ [V] [DP$_j$ [,phantom,tier=word]]]]]]]]]]]]]] }{\forest@includeexternal@check {germanic-forest-37}}{\forest@includeexternal {germanic-forest-37}}
\forest@external {38}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \sliste { }} [{NP[\type {snom}]} [der Mann;the man, roof] ] [V\feattab { \sliste { NP[\type {snom}] }} [{NP[\type {sacc}]} [den Jungen;the boy, roof] ] [V\feattab { \sliste { NP[\type {snom}], NP[\type {sacc}]}} [{NP[\type {sacc}]} [den Aufsatz;the paper, roof] ] [V\feattab { \sliste { NP[\type {snom}], NP[\type {sacc}], NP[\type {sacc}]}} [~~~~~~V\feattab { \sliste { NP[\type {sacc}], NP[\type {sacc}]}} [lesen;read] ] [V\feattab { \sliste { NP[\type {snom}], NP[\type {sacc}], NP[\type {sacc}], V }} [lässt;lets] ] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-38}}{\forest@includeexternal {germanic-forest-38}}
\forest@external {39}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [S [{NP[\type {snom}]} [the man, roof] ] [VP [\vbar [V [let] ] [{NP[\type {sacc}]} [the boy] ] ] [VP [V [read] ] [{NP[\type {sacc}]} [the book, roof] ] ] ] ] }{\forest@includeexternal@check {germanic-forest-39}}{\forest@includeexternal {germanic-forest-39}}
\forest@external {40}{dj,9.51996pt,0.4pt,.3333em,.5\pgflinewidth ,.3333em,.5\pgflinewidth @@ sm edges [V\feattab { \vform \type {fin},\\ \comps \ibox {1} } [{\ibox {3} V\feattab { \vform \type {ppp},\\ \subj \ibox {1},\\ \comps \eliste }} [{\ibox {2} V\feattab { \vform \type {inf},\\ \subj \sliste { NP[\str ] }, \\ \comps \ibox {1} \sliste { NP[\str ] } }} [zu reparieren] ] [V\feattab { \vform \type {ppp},\\ \subj \ibox {1},\\ \comps \sliste { \ibox {2} } } [versucht] ] ] [V\feattab { \vform \type {fin},\\ \comps \ibox {1} $\oplus $ \sliste { \ibox {3} }} [wurde] ] ] }{\forest@includeexternal@check {germanic-forest-40}}{\forest@includeexternal {germanic-forest-40}}

